### ISSUE TITLE
PHP 7+ support?

### ISSUE THREAD

**Issue by jeffkarney** [intuit/QuickBooks-V3-PHP-SDK#249]
Has anyone tried using this with PHP 7+? There is so much old and just wrong code here it seems like Intuit just doesn't care.

The ancient XSD2PHP\src\com\mikebevz\xsd2php library straight up fails making the SDK completely useless with any modern PHP environment. The [latest version](https://github.com/goetas/xsd2php) of it was deprecated/abandoned on Sep 26, 2016. And the version in this SDK is probably from 2010.

Should I just not use this SDK? Should I put some work into modernizing it? Should Intuit put a competent dev on it for a day or 2 to modernize it?

Curious what others are doing.

**Comment by aknosis** [comment]
I'm using this SDK on 7.3 and haven't had any issues.

- Is it the best PHP SDK I've ever used? No.
- Is it better than interfacing with the API directly? Most likely, yes.

- Do **you** have to use it? No.

**Comment by ianjohn27** [comment]
`remote:   - info: checking wp-content/plugins/expressrez/vendor/quickbooks/v3-php-sdk/src/XSD2PHP/test/data/expected/Xsd2Php/MavenTests/bindings/org/apache/maven/POM/_4_0_0/Parent.php ...
remote: PHP Fatal error:  Cannot use 'Parent' as class name as it is reserved in Standard input code on line 11
remote:   - warning: syntax Error Found in wp-content/plugins/xxxxxx/vendor/quickbooks/v3-php-sdk/src/XSD2PHP/test/data/expected/Xsd2Php/MavenTests/bindings/org/apache/maven/POM/_4_0_0/Parent.php ...
`

So yeah, if you want to use this with a wordpress plugin, and you host with WPEngine, you might want to consider other options.

**Comment by bsivalingam** [comment]
Our team has decided to just work on minor version updates and schema changes for this SDK. We will only be fixing breaking changes. That said, I would love to upgrade the XSD2PHP package to the most current version in the next release, but no promises.

**Comment by Benjaminhu** [comment]
```
$ composer require quickbooks/v3-php-sdk
  Problem 1
    - The requested PHP extension ext-mcrypt * is missing from your system. Install or enable PHP's mcrypt extension.

$ php --version
PHP 7.2.24
```

PHP Manual -> Function Reference -> Cryptography Extensions -> [Mcrypt](https://www.php.net/manual/en/intro.mcrypt.php)

> **Warning
This feature was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.**

**Comment by matt-d** [comment]
Using SDK V3 on PHP 7.0 I can't seem to make this example work:

https://github.com/IntuitDeveloper/SampleApp-CRUD-PHP/blob/master/CRUD_Examples/Invoice/InvoiceCreate.php

Seems related to the xsd2php library - specificallly this bit:

https://github.com/intuit/QuickBooks-V3-PHP-SDK/blob/master/src/XSD2PHP/src/com/mikebevz/xsd2php/Php2Xml.php#L96

Am I missing something, or is it impossible to post an invoice with this SDK on PHP 7+?

**Comment by bsivalingam** [comment]
@Benjaminhu you should be able to get unblocked if you install mcrypt. Mcrypt has been moved out of PHP yes, but extensions are available. Are you able to try installing it? 

@matt-d I have heard from other developers that they didn't have issues using the SDK on PHP 7+. But like I mentioned above we would like to upgrade to more recent XSD2PHP library.

**Comment by Benjaminhu** [comment]
@bsivalingam I tried again today and we installed it successfully, I deleted it with the previous comment, thanks!

**Comment by bsivalingam** [comment]
@Benjaminhu Are willing to share the steps you took to fix the issue? It will be helpful for others running into it in the future. Thanks.

**Comment by Benjaminhu** [comment]
@bsivalingam I'm sorry, it was only me that made the mistake.
I tested several things and wasn’t entirely careful!
I checked the "QuickBooks-V3-PHP-SDK" package **does not contain "mcrypt *" features**.
So I must have had a composer.json condition that caused this.
Please take it as irrelevant! Thanks and sorry.

**Comment by matt-d** [comment]
> @matt-d I have heard from other developers that they didn't have issues using the SDK on PHP 7+. But like I mentioned above we would like to upgrade to more recent XSD2PHP library.

@Benjaminhu - thanks for the reply - are you able to make that example code run on PHP 7.0?  Other code seems to work fine, as long as the objects are not nested - as in that example.  I'm able to insert other types of objects and query / fetch them without issue.  The Invoice object requires a Line property, which is an array, which contains an array SalesItemLineDetail, which contains an array ItemRef.  This is the issue it seems - the level of nesting is not supported by the SDK - so I don't think the example code works.

https://github.com/IntuitDeveloper/SampleApp-CRUD-PHP/blob/master/CRUD_Examples/Invoice/InvoiceCreate.php#L26

Do you have example code for Invoice creation using the SDK with PHP 7+?

**Comment by levinse** [comment]
No problems whatsoever with the SDK on PHP 7.3

**Comment by bsivalingam** [comment]
@matt-d No I do not have an example code for Invoice creation. Are you still blocked? 

@levinse And the error is now fixed is that right?

**Comment by bsivalingam** [comment]
Closing issue.

**Comment by Wirone** [comment]
It breaks analysis of [`ComposerRequireChecker`](https://github.com/maglnet/ComposerRequireChecker):

```
❯ php bin/composer-require-checker
ComposerRequireChecker 3.3.0@4063254c611acf34f1c15b29b6bcc47d2e7a9a9e

In LocateASTFromFiles.php line 46:

Parsing the file [app/vendor/quickbooks/v3-php-sdk/src/XSD2PHP/test/data/expected/Xsd2Php/MavenTests/bindings/org/apache/maven/POM/_4_0_0/Parent.php] resulted in an error: Cannot use 'Parent' as class name as it is reserved on line 11

In ParserAbstract.php line 919:

Cannot use 'Parent' as class name as it is reserved on line 11

check [--config-file CONFIG-FILE] [--ignore-parse-errors] [--] [<composer-json>]
```

And yeah, `--ignore-parse-errors` can be used, but I just wanted to point that problem still exists 😉
