### ISSUE TITLE
IPPFault not parsed

### ISSUE THREAD

**Issue by challgren** [intuit/QuickBooks-V3-PHP-SDK#7]
It would be nice, if there is an API error to parse the response into an IPPFault. I've tried to use XmlObjectSerializer::Deserialize($response). Looks like on line 239 of XmlObjectSerializer there is code to return null if it encounters a Fault.

**Comment by hlu2** [comment]
I will mark it on my working list.

**Comment by TimOgilvy** [comment]
This is actually crazy.

Intuit need to make it much much clearer everywhere on their website that this SDK is an incredibly incomplete Beta. I understand that it takes time to build these things, and the github repo is reasonably clear that there are no stable releases for this SDK, but the marketing and developer portal parts of the intuit and intuit developer sites do not have enough clear disclaimers to this fact.  If they want to flog this thing as a feature, they need to pay y'all some more to finish it!

**Comment by hlu2** [comment]
@all
It is in progress now

**Comment by hlu2** [comment]
@ALL
Fixed on v3.2.6

**Comment by challgren** [comment]
I'm still getting unparsed Faults on version 3.4.0


```
REQUEST URI FOR SEQUENCE ID 00034
==================================
https://quickbooks.api.intuit.com/v3/company/1376871555/query?minorversion=12

REQUEST HEADERS
================
Authorization: OAuth oauth_consumer_key="******",oauth_token="*******",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1504559503",oauth_nonce="****",oauth_version="1.0",oauth_signature="********"
host: quickbooks.api.intuit.com
user-agent: V3PHPSDK3.4.0
accept: */*
connection: close
content-type: application/text
content-length: 53

REQUEST BODY
=============
select * from Estimate startPosition 1 maxResults 500

```

```
RESPONSE URI FOR SEQUENCE ID 00035
==================================
https://quickbooks.api.intuit.com/v3/company/1376871555/query?minorversion=12

RESPONSE HEADERS
================
Server: nginx
Date: Mon, 04 Sep 2017 21:11:44 GMT
Content-Type: application/xml;charset=UTF-8
Content-Length: 478
Connection: close
Strict-Transport-Security: max-age=15552000
intuit_tid: 8750a82a-05fc-4680-d072-f8340b8642c7
QBO-Version: 1707.981
Cache-Control: max-age=0, no-cache, no-store, must-revalidate, private
Expires: 0
Service-Time: total=228, db=187

RESPONSE BODY
=============
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><IntuitResponse xmlns="http://schema.intuit.com/finance/v3" time="2017-09-04T14:11:44.321-07:00"><Fault type="SystemFault"><Error code="10000"><Message>An application error has occurred while processing your request</Message><Detail>System Failure Error: Something you're trying to use has been made inactive. Check the fields with accounts, customers, items, vendors or employees.</Detail></Error></Fault></IntuitResponse>

```

My code is

```
$estimates = $this->QboDataService->FindAll('Estimate', $i, 500);
$error = $this->QboDataService->getLastError();
debug($error);
```

When I execute the code the $error is returning as null and $estimates is returning null. I would expect the $error to return a IPPFault.

**Comment by challgren** [comment]
This also brings up another issue. Is there a way to maybe to log the request method. And when trying the API explorer on developer.intuit.com the query works fine because its a get with a query parameter. This is a POST request that is failing did maybe the QBO API get updated and not the SDK?

**Comment by challgren** [comment]
Ok so I switched from FindAll() to Query() now the error is Notice Error: Undefined variable: tmpXML in [/Users/challgren/Projects/ATX Liquor/website v1/Vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php, line 804]

If I uncomment line 803

The following is the response

```
object(SimpleXMLElement)#69 (2) {
  ["@attributes"]=>
  array(1) {
    ["time"]=>
    string(29) "2017-09-04T14:56:05.485-07:00"
  }
  ["Fault"]=>
  object(SimpleXMLElement)#74 (2) {
    ["@attributes"]=>
    array(1) {
      ["type"]=>
      string(11) "SystemFault"
    }
    ["Error"]=>
    object(SimpleXMLElement)#75 (3) {
      ["@attributes"]=>
      array(1) {
        ["code"]=>
        string(5) "10000"
      }
      ["Message"]=>
      string(63) "An application error has occurred while processing your request"
      ["Detail"]=>
      string(148) "System Failure Error: Something you're trying to use has been made inactive. Check the fields with accounts, customers, items, vendors or employees."
    }
  }
}
Notice Error: Undefined variable: tmpXML in [/Users/challgren/Projects/ATX Liquor/website v1/Vendor/quickbooks/v3-php-sdk/src/DataService/DataService.php, line 804]

```

**Comment by challgren** [comment]
Ok so the fault was generated cause I was trying to use minorVersion 12 I tried minorVersion 11 which says its supported and still got the error. The resolution was to set minorVersion to 8
